server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      max-file-size: 10MB  #单个文件
      max-request-size: 100MB #总文件大小

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://47.100.240.13:3306/db_integrity?useSSL=false&characterEncoding=UTF-8
      url: jdbc:mysql://10.255.195.63:3306/db_newintegrity?useSSL=false&characterEncoding=UTF-8
      username: root
      password: zx19961215
      #password: zx19961215
      #使用druid数据库连接池
#      type: com.alibaba.druid.pool.DruidDataSource
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20
   jpa:
     show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iotlab.integrityarchives.entity

#thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

    #devtools插件
  devtools:
    restart:
      enabled: true #是否支持热部署
#mybaatis分页插件pagehelper设置
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true

  # 打印sql
logging:
    level:
       com.iotlab.integrityarchives.dao: DEBUG

application:
  #文件上传路径
  profile: F:/IntegrityArchivesUpload/